@startuml

[*] --> Off: Install

state Broken
state On
state Off
state BrokenDecision <<choice>>

Off --> On: Switch on
On --> Off: Switch off
On --> Broken: Break
Broken --> BrokenDecision
BrokenDecision --> Off: Replace
BrokenDecision --> [*]: Remove
Off --> [*] : Remove

@enduml
