@startuml
[*] --> Open: Create

state Open

state Closed {
    state Locked
    [*] --> Locked: Lock
    Locked --> [*]: Unlock
}

Open --> Closed : Close
Closed --> Open : Open
Closed --> [*] : Destroy
Open --> [*] : Destroy

@enduml